### ISSUE TITLE
Spanner primary key strategy compliance

### ISSUE THREAD

**Issue by gabrizappts** [googleapis/python-spanner-sqlalchemy#181]
Hi!
I'd like to know which strategy should be applied in order to create and insert primary keys using python-spanner-sqlalchemy, since the standard documentation recommends [against the usage of auto-increment ids](https://cloud.google.com/spanner/docs/schema-and-data-model), although looking into the library's samples I've come across the following row insertion snippet:
`
def insert_row(connection, table):
    """Insert row into the table.
    The table must already exist and can be created using
    `create_table.`
    """
    connection.execute(table.insert(), {"user_id": 1, "user_name": "ABC"})

    row = list(connection.execute(table.select()))

    print("Inserted row: ", row)
`
    
That resembles the usage of auto-increment primary keys in SQLAlchemy's documentation, but being migrating from a regular database provider (Postgres), I don't know if it would be a good practice to just translate the current tables with auto-increment indexes to Cloud Spanner.

**Comment by skuruppu** [comment]
@gabrizappts good timing because we were just talking about this in #176.

In general, yes, you're right that Cloud Spanner discourages you from using auto-incrementing IDs. As per an example in [our blog](https://cloud.google.com/blog/topics/developers-practitioners/google-cloud-spanner-dialect-sqlalchemy), we recommend that you generate a UUID for primary keys. I will update our README to mention this as well and the code snippet you mentioned.

In case you have a really good reason to use auto-incrementing PKs, we added [this section](https://github.com/googleapis/python-spanner-sqlalchemy#autoincremented-ids) to show how you might achieve that.

Hope that helps.

**Comment by gabrizappts** [comment]
Thanks for your response, @skuruppu.

It helped me a lot :)
