### ISSUE TITLE
Release on pypi

### ISSUE THREAD

**Issue by hadim** [googleapis/python-spanner-sqlalchemy#58]
Could a version be released on pypi or a git tag added to the repo? I would like to package this lib on conda forge.

**Comment by skuruppu** [comment]
@hadim absolutely. At the moment, we are focusing on getting the preview release milestone. But shortly after that, we'll work on getting the packages into pypi. Let us know if this is urgent for you though.

**Comment by hadim** [comment]
It's not urgent. Just ping me here when it's done and I will make the conda forge package.

**Comment by aderk** [comment]
@skuruppu I need to package python-spanner-sqlalchemy for deployment. I can either vendor the package privately, or submit a PR here to create a [pre-release](https://packaging.python.org/guides/distributing-packages-using-setuptools/#pre-release-versioning) on PyPI. Would you be open to the latter? Could you give me some high-level steps? Thanks!

**Comment by hadim** [comment]
To me that lib is quite mature already. I am using it in production. A git+pip release would be nice indeed.

**Comment by skuruppu** [comment]
@hadim that's great to hear. Please do file issues, especially if you run into perf issues.

@aderk we were due to cut a pre-release a week or so ago but we had to investigate a potential DDL performance issue so we're going to look into that first before adding the git tag. Really sorry for the delay on this but we're working on the investigation.

In terms of publishing to PyPI, I realize that this is going to be a bit more complicated. We need to setup some scripts that would fetch passwords for publishing to PyPI as Google Cloud. I will need to move this repo to its final home under github.com/googleapis before I can do that.

In the meantime, do you think it's possible for you to create the package privately? Or is there some other way that we can create one and share it with you?

**Comment by aderk** [comment]
I can create it privately no problem, best of luck with cutting the release. Cheers

**Comment by hadim** [comment]
I have created a conda package using the 0.1.0 tag. See https://github.com/conda-forge/sqlalchemy-spanner-feedstock. Please make a PR to the feedstock if you want to be added as a maintainer.

**Comment by aderk** [comment]
I am unable to find this package on PyPI. Do you know when it will be available?

**Comment by skuruppu** [comment]
@aderk really sorry about this. I merged in the PR that was meant to trigger the release process but it never worked. I'm working on it today so fingers crossed that we have a release available within a day or so.

**Comment by skuruppu** [comment]
I managed to create a release on [PyPI](https://pypi.org/project/sqlalchemy-spanner/0.1.dev0/). Not quite the version number that I wanted to create so I will fix that up but hopefully it's a start.

**Comment by aderk** [comment]
The package I vendored has the exact same version (0.1.dev0) causing a version collision in pip making using PyPI difficult. A version bump on PyPI would be great!

**Comment by skuruppu** [comment]
Ah, sorry about that @aderk. We're in a release freeze at the moment due to the holidays in the US. But I will try to cut another release on the 1st once we come out of the freeze.

**Comment by skuruppu** [comment]
Really sorry for the delay @aderk but I just thought that it might make more sense to take the time to do a v1.0 release. Now it's available on PyPI: https://pypi.org/project/sqlalchemy-spanner/ :)

Please let us know if you run into any trouble with it. I will close the issue now as we have the releases setup properly.
